import type { AlgorithmCategory, AlgorithmType, Snapshot } from '../../types';
import {
  generateAdjacencyListTrace,
  generateAdjacencyMatrixTrace,
  generateBFSTrace,
  generateDFSTrace,
  generateDijkstraTrace,
  generateFloydWarshallTrace,
  generateKruskalTrace,
  generatePrimTrace,
  generateTopologicalSortTrace,
  generateWarshallTrace,
} from './graph';
import {
  generateBacktrackingTrace,
  generateBranchAndBoundTrace,
  generateBruteForceTrace,
  generateDivideAndConquerTrace,
  generateDynamicProgrammingTrace,
  generateGreedyAlgorithmsTrace,
  generateRandomizedAlgorithmsTrace,
  generateRecursiveAlgorithmsTrace,
} from './design';
import {
  generateBubbleSortTrace,
  generateHeapSortTrace,
  generateInsertionSortTrace,
  generateMergeSortTrace,
  generateQuickSortTrace,
  generateSelectionSortTrace,
  generateShellSortTrace,
  generateRadixSortTrace,
} from './sorting';
import {
  generateCircularLinkedListTrace,
  generateDoublyLinkedListTrace,
  generateSinglyLinkedListTrace,
} from './linkedList';
import {
  generateCircularQueueTrace,
  generateDequeTrace,
  generateLinearQueueTrace,
  generatePriorityQueueTrace,
} from './queue';
import {
  generateBinaryTreeTraversalsTrace,
  generateAVLRotationsTrace,
  generateBTreeInsertionTrace,
  generateBSTInsertSearchDeleteTrace,
  generateHuffmanCodingTrace,
  generateRedBlackIntroTrace,
} from './tree';
import {
  generateExpressionConversionTrace,
  generateFactorialRecursionTrace,
  generateFibonacciRecursionTrace,
  generatePostfixEvaluationTrace,
  generatePrefixEvaluationTrace,
  generateStackPushPopTrace,
  generateTowerOfHanoiTrace,
} from './stackRecursion';
import {
  generateBinarySearchTrace as generateBinarySearchTraceSearch,
  generateHashTableChainingTrace,
  generateHashTableDoubleHashingTrace,
  generateHashTableLinearProbingTrace,
  generateHashTableQuadraticProbingTrace,
  generateHashingTrace,
  generateSequentialSearchTrace,
} from './search';

export const algorithmGenerators: Record<AlgorithmType, (array: number[]) => Snapshot[]> = {
  'brute-force': generateBruteForceTrace,
  'divide-and-conquer': generateDivideAndConquerTrace,
  'greedy-algorithms': generateGreedyAlgorithmsTrace,
  'branch-and-bound': generateBranchAndBoundTrace,
  'backtracking': generateBacktrackingTrace,
  'randomized-algorithms': generateRandomizedAlgorithmsTrace,
  'recursive-algorithms': generateRecursiveAlgorithmsTrace,
  'dynamic-programming': generateDynamicProgrammingTrace,
  'stack-push-pop': generateStackPushPopTrace,
  'expression-conversion': generateExpressionConversionTrace,
  'postfix-evaluation': generatePostfixEvaluationTrace,
  'prefix-evaluation': generatePrefixEvaluationTrace,
  'factorial-recursion': generateFactorialRecursionTrace,
  'fibonacci-recursion': generateFibonacciRecursionTrace,
  'tower-of-hanoi': generateTowerOfHanoiTrace,
  'linear-queue': generateLinearQueueTrace,
  'circular-queue': generateCircularQueueTrace,
  'deque': generateDequeTrace,
  'priority-queue': generatePriorityQueueTrace,
  'singly-linked-list': generateSinglyLinkedListTrace,
  'doubly-linked-list': generateDoublyLinkedListTrace,
  'circular-linked-list': generateCircularLinkedListTrace,
  'binary-tree-traversals': generateBinaryTreeTraversalsTrace,
  'bst-insert-search-delete': generateBSTInsertSearchDeleteTrace,
  'avl-rotations': generateAVLRotationsTrace,
  'b-tree-insertion': generateBTreeInsertionTrace,
  'red-black-intro': generateRedBlackIntroTrace,
  'huffman-coding': generateHuffmanCodingTrace,
  'adjacency-matrix': generateAdjacencyMatrixTrace,
  'adjacency-list': generateAdjacencyListTrace,
  'bfs': generateBFSTrace,
  'dfs': generateDFSTrace,
  'dijkstra': generateDijkstraTrace,
  'floyd-warshall': generateFloydWarshallTrace,
  'kruskal': generateKruskalTrace,
  'prim': generatePrimTrace,
  'warshall': generateWarshallTrace,
  'topological-sort': generateTopologicalSortTrace,
  'bubble-sort': generateBubbleSortTrace,
  'insertion-sort': generateInsertionSortTrace,
  'selection-sort': generateSelectionSortTrace,
  'shell-sort': generateShellSortTrace,
  'quick-sort': generateQuickSortTrace,
  'merge-sort': generateMergeSortTrace,
  'radix-sort': generateRadixSortTrace,
  'heap-sort': generateHeapSortTrace,
  'sequential-search': generateSequentialSearchTrace,
  'binary-search': generateBinarySearchTraceSearch,
  'hashing': generateHashingTrace,
  'hash-table-chaining': generateHashTableChainingTrace,
  'hash-table-linear-probing': generateHashTableLinearProbingTrace,
  'hash-table-quadratic-probing': generateHashTableQuadraticProbingTrace,
  'hash-table-double-hashing': generateHashTableDoubleHashingTrace,
};

export const algorithmGroups: Array<{
  category: AlgorithmCategory;
  label: string;
  items: Array<{ id: AlgorithmType; label: string; description: string }>;
}> = [
  {
    category: 'design-techniques',
    label: 'Design Techniques',
    items: [
      { id: 'brute-force', label: 'Brute Force', description: 'Try every possible option until the correct solution appears.' },
      { id: 'divide-and-conquer', label: 'Divide & Conquer', description: 'Split the problem into independent subproblems and combine results.' },
      { id: 'greedy-algorithms', label: 'Greedy Algorithms', description: 'Choose locally optimal moves toward a fast global solution.' },
      { id: 'branch-and-bound', label: 'Branch & Bound', description: 'Explore a search tree while pruning paths using bounds.' },
      { id: 'backtracking', label: 'Backtracking', description: 'Try partial solutions and retreat when they fail.' },
      { id: 'randomized-algorithms', label: 'Randomized Algorithms', description: 'Use randomness to improve expected performance.' },
      { id: 'recursive-algorithms', label: 'Recursive Algorithms', description: 'Solve problems by repeating the same logic on smaller inputs.' },
      { id: 'dynamic-programming', label: 'Dynamic Programming', description: 'Cache overlapping subproblems to avoid duplicate work.' },
    ],
  },
  {
    category: 'stack-recursion',
    label: 'Stacks & Recursion',
    items: [
      { id: 'stack-push-pop', label: 'Stack Push/Pop', description: 'Visualize LIFO stack operations and top-of-stack behavior.' },
      { id: 'expression-conversion', label: 'Infix → Postfix', description: 'Convert an arithmetic expression using operator precedence.' },
      { id: 'postfix-evaluation', label: 'Postfix Evaluation', description: 'Evaluate a postfix expression with stack-based computation.' },
      { id: 'prefix-evaluation', label: 'Prefix Evaluation', description: 'Process a prefix expression from right to left with a stack.' },
      { id: 'factorial-recursion', label: 'Factorial Recursion', description: 'Trace the recursion stack for n! computation.' },
      { id: 'fibonacci-recursion', label: 'Fibonacci Recursion', description: 'See recursive calls expand and collapse for Fibonacci.' },
      { id: 'tower-of-hanoi', label: 'Tower of Hanoi', description: 'Visualize recursive moves between three pegs.' },
    ],
  },
  {
    category: 'queue',
    label: 'Queues',
    items: [
      { id: 'linear-queue', label: 'Linear Queue', description: 'Basic queue operations on a fixed linear buffer.' },
      { id: 'circular-queue', label: 'Circular Queue', description: 'Wrap queue operations around a ring buffer.' },
      { id: 'deque', label: 'Deque', description: 'Double-ended queue operations on both front and back.' },
      { id: 'priority-queue', label: 'Priority Queue', description: 'Visualize highest-priority items rising to the top.' },
    ],
  },
  {
    category: 'linked-list',
    label: 'Linked Lists',
    items: [
      { id: 'singly-linked-list', label: 'Singly Linked List', description: 'Traverse a linked list in one direction.' },
      { id: 'doubly-linked-list', label: 'Doubly Linked List', description: 'Traverse forwards and backwards through nodes.' },
      { id: 'circular-linked-list', label: 'Circular Linked List', description: 'Visualize a looped list where tail connects to head.' },
    ],
  },
  {
    category: 'tree',
    label: 'Trees',
    items: [
      { id: 'binary-tree-traversals', label: 'Binary Tree Traversal', description: 'Explore preorder, inorder, and postorder walks.' },
      { id: 'bst-insert-search-delete', label: 'BST Insert/Search/Delete', description: 'Simulate a binary search tree operation sequence.' },
      { id: 'avl-rotations', label: 'AVL Rotations', description: 'See tree rotations that restore balance.' },
      { id: 'b-tree-insertion', label: 'B-Tree Insertion', description: 'Insert values and split nodes in a B-tree.' },
      { id: 'red-black-intro', label: 'Red-Black Intro', description: 'Watch color balancing rules for red-black trees.' },
      { id: 'huffman-coding', label: 'Huffman Coding', description: 'Combine frequencies into a prefix code tree.' },
    ],
  },
  {
    category: 'graph',
    label: 'Graphs',
    items: [
      { id: 'adjacency-matrix', label: 'Adjacency Matrix', description: 'Represent graph connectivity as a matrix.' },
      { id: 'adjacency-list', label: 'Adjacency List', description: 'Store adjacency using lists of neighbor nodes.' },
      { id: 'bfs', label: 'Breadth-First Search', description: 'Traverse the graph layer by layer.' },
      { id: 'dfs', label: 'Depth-First Search', description: 'Explore each branch deeply before backtracking.' },
      { id: 'dijkstra', label: 'Dijkstra', description: 'Compute shortest paths from a source node.' },
      { id: 'floyd-warshall', label: 'Floyd-Warshall', description: 'Calculate all-pairs shortest paths using dynamic updates.' },
      { id: 'kruskal', label: 'Kruskal', description: 'Build a minimum spanning tree by edge weight.' },
      { id: 'prim', label: 'Prim', description: 'Grow a minimum spanning tree from a starting node.' },
      { id: 'warshall', label: 'Warshall', description: 'Compute reachability closure of a directed graph.' },
      { id: 'topological-sort', label: 'Topological Sort', description: 'Order vertices in a directed acyclic graph.' },
    ],
  },
  {
    category: 'sorting',
    label: 'Sorting',
    items: [
      { id: 'bubble-sort', label: 'Bubble Sort', description: 'Repeatedly swap adjacent out-of-order elements.' },
      { id: 'insertion-sort', label: 'Insertion Sort', description: 'Build a sorted prefix one element at a time.' },
      { id: 'selection-sort', label: 'Selection Sort', description: 'Select the minimum remaining element each round.' },
      { id: 'shell-sort', label: 'Shell Sort', description: 'Use gap-sorted subsequences to improve insertion speed.' },
      { id: 'quick-sort', label: 'Quick Sort', description: 'Partition around pivots and sort subarrays recursively.' },
      { id: 'merge-sort', label: 'Merge Sort', description: 'Divide array and merge sorted halves back together.' },
      { id: 'radix-sort', label: 'Radix Sort', description: 'Sort numbers by processing digits from least to most significant.' },
      { id: 'heap-sort', label: 'Heap Sort', description: 'Use a binary heap to repeatedly extract the largest element.' },
    ],
  },
  {
    category: 'searching',
    label: 'Searching',
    items: [
      { id: 'sequential-search', label: 'Sequential Search', description: 'Scan each element until the target is found.' },
      { id: 'binary-search', label: 'Binary Search', description: 'Halve the search range on a sorted array.' },
      { id: 'hashing', label: 'Hashing', description: 'Place values into buckets using a hash function.' },
      { id: 'hash-table-chaining', label: 'Hash Table Chaining', description: 'Resolve collisions by building chains inside buckets.' },
      { id: 'hash-table-linear-probing', label: 'Linear Probing', description: 'Resolve collisions by scanning sequential bucket slots.' },
      { id: 'hash-table-quadratic-probing', label: 'Quadratic Probing', description: 'Probe using a quadratic step size to resolve collisions.' },
      { id: 'hash-table-double-hashing', label: 'Double Hashing', description: 'Use a second hash function to disperse collisions.' },
    ],
  },
];
